checks:
  file-lines:
    enabled: false

engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 50
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
    - "**.py"
    - "**.md"

exclude_paths:
  - "git-hooks/"
  - "data/"
  - "tests/"
  - "pylintrc"
