notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

language: python
python:
  - "3.6"

install:
  - pip install nose coverage
  - pip install progressbar2
  - pip install xlrd

script:
  - nosetests --with-coverage --cover-erase --cover-package=cgp_seq_input_val
